// Generated By db to  class
package model;

public class Category implements java.io.Serializable {

	public Category() {
	}

	private int id;
	private String cname;
	private String description;
	private String keywords;
	private String title;

	public int getId() {
		return id;
	}

	public void setId(int value) {
		id = value;
	}

	public String getCname() {
		return cname;
	}

	public void setCname(String value) {
		cname = value;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String value) {
		description = value;
	}

	public String getKeywords() {
		return keywords;
	}

	public void setKeywords(String value) {
		keywords = value;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String value) {
		title = value;
	}
}