// default package
// Generated Apr 11, 2014 10:39:23 PM by Hibernate Tools 4.0.0
package model;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "fazlastoklar")
public class Category implements java.io.Serializable {

	private Integer id;
	private String cname;
	private Set<Productcategory> productcategories = new HashSet<Productcategory>(
			0);

	public Category() {
	}

	public Category(String cname, Set<Productcategory> productcategories) {
		this.cname = cname;
		this.productcategories = productcategories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cname")
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Productcategory> getProductcategories() {
		return this.productcategories;
	}

	public void setProductcategories(Set<Productcategory> productcategories) {
		this.productcategories = productcategories;
	}

}
