// Generated By db to  class
package model;

import java.util.Date;

import javax.validation.constraints.Future;
import javax.validation.constraints.Min;

public class Product implements java.io.Serializable {

	public Product() {
	}

	private Integer id = 0;
	private Integer userid;
	private String pname;
	private String content;
	private String pstate;
	private String quantity;

	@Min(value = 1000, message = "{priceTooLow}")
	private Integer price;
	@Future(message = "{dateFuture}")
	private Date expiredate;

	private String keywords;
	private String file;
	private Integer adet;
	private Integer kg;
	private Integer m3;
	private Integer kalem;

	private Integer pprice;

	public Integer getId() {
		return id;
	}

	public void setId(Integer value) {
		id = value;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer value) {
		userid = value;
	}

	public String getPname() {
		return pname;
	}

	public void setPname(String value) {
		pname = value;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String value) {
		content = value;
	}

	public String getPstate() {
		return pstate;
	}

	public void setPstate(String value) {
		pstate = value;
	}

	public String getQuantity() {
		return quantity;
	}

	public void setQuantity(String value) {
		quantity = value;
	}

	public Integer getPrice() {
		return price;
	}

	public void setPrice(Integer value) {
		price = value;
	}

	public Date getExpiredate() {
		return expiredate;
	}

	public void setExpiredate(Date value) {
		expiredate = value;
	}

	public String getKeywords() {
		return keywords;
	}

	public void setKeywords(String value) {
		keywords = value;
	}

	public String getFile() {
		return file;
	}

	public void setFile(String value) {
		file = value;
	}

	public Integer getAdet() {
		return adet;
	}

	public void setAdet(Integer value) {
		adet = value;
	}

	public Integer getKg() {
		return kg;
	}

	public void setKg(Integer value) {
		kg = value;
	}

	public Integer getM3() {
		return m3;
	}

	public void setM3(Integer value) {
		m3 = value;
	}

	public Integer getKalem() {
		return kalem;
	}

	public void setKalem(Integer value) {
		kalem = value;
	}

	public Integer getPprice() {
		System.out.println("pprice:"+pprice);
		return pprice;
	}

	public void setPprice(Integer value) {
		pprice = value;
	}
}