// default package
// Generated Apr 11, 2014 10:39:23 PM by Hibernate Tools 4.0.0
package model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Productcategory generated by hbm2java
 */
@Entity
@Table(name = "productcategory", catalog = "fazlastoklar")
public class Productcategory implements java.io.Serializable {

	private Integer id;
	private Category category;
	private Product product;

	public Productcategory() {
	}

	public Productcategory(Product product) {
		this.product = product;
	}

	public Productcategory(Category category, Product product) {
		this.category = category;
		this.product = product;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoryId")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}
