// Generated By db to  class
package model;

import java.util.Date;

public class Product implements java.io.Serializable {

	public Product() {
	}

	private int id=0;
	private int userid;
	private String pname;
	private String content;
	private String pstate;
	private String quantity;
	private int price;
	private Date expiredate;
	private String keywords;
	private String file;
	private int adet;
	private int kg;
	private int m3;
	private int kalem;
	private int pprice;

	public int getId() {
		return id;
	}

	public void setId(int value) {
		id = value;
	}

	public int getUserid() {
		return userid;
	}

	public void setUserid(int value) {
		userid = value;
	}

	public String getPname() {
		return pname;
	}

	public void setPname(String value) {
		pname = value;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String value) {
		content = value;
	}

	public String getPstate() {
		return pstate;
	}

	public void setPstate(String value) {
		pstate = value;
	}

	public String getQuantity() {
		return quantity;
	}

	public void setQuantity(String value) {
		quantity = value;
	}

	public int getPrice() {
		return price;
	}

	public void setPrice(int value) {
		price = value;
	}

	public Date getExpiredate() {
		return expiredate;
	}

	public void setExpiredate(Date value) {
		expiredate = value;
	}

	public String getKeywords() {
		return keywords;
	}

	public void setKeywords(String value) {
		keywords = value;
	}

	public String getFile() {
		return file;
	}

	public void setFile(String value) {
		file = value;
	}

	public int getAdet() {
		return adet;
	}

	public void setAdet(int value) {
		adet = value;
	}

	public int getKg() {
		return kg;
	}

	public void setKg(int value) {
		kg = value;
	}

	public int getM3() {
		return m3;
	}

	public void setM3(int value) {
		m3 = value;
	}

	public int getKalem() {
		return kalem;
	}

	public void setKalem(int value) {
		kalem = value;
	}

	public int getPprice() {
		return pprice;
	}

	public void setPprice(int value) {
		pprice = value;
	}
}