// default package
// Generated Apr 11, 2014 10:39:23 PM by Hibernate Tools 4.0.0
package model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Productphoto generated by hbm2java
 */
@Entity
@Table(name = "productphoto", catalog = "fazlastoklar", uniqueConstraints = @UniqueConstraint(columnNames = "productId"))
public class Productphoto implements java.io.Serializable {

	private Integer id;
	private Integer productid;
	private String file;

	public Productphoto() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId", unique = true)
	public Integer getProduct() {
		return this.productid;
	}

	public void setProduct(Integer product) {
		this.productid = product;
	}

	@Column(name = "file")
	public String getFile() {
		return this.file;
	}

	public void setFile(String file) {
		this.file = file;
	}

}
