// Generated By db to  class
package model;

public class State implements java.io.Serializable {

	public State() {
	}

	public State(String sname) {
		this.sname = sname;
	}

	private int id;
	private String sname;

	public int getId() {
		return id;
	}

	public void setId(int value) {
		id = value;
	}

	public String getSname() {
		return sname;
	}

	public void setSname(String value) {
		sname = value;
	}
}