// Generated By db to  class
package model;

public class Talep implements java.io.Serializable {

	
	public Talep() {
	}

	private int id;
	private int productid;
	private int userid;
	private String name;
	private String email;
	private String gsm;
	private String notes;
	private int state;
	private String firmaname;
	private String pname;
	private String uname;

	public String getFirmaname() {
		return firmaname;
	}

	public void setFirmaname(String firmaname) {
		this.firmaname = firmaname;
	}

	public String getPname() {
		return pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getUname() {
		return uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public int getId() {
		return id;
	}

	public void setId(int value) {
		id = value;
	}

	public int getProductid() {
		return productid;
	}

	public void setProductid(int value) {
		productid = value;
	}

	public int getUserid() {
		return userid;
	}

	public void setUserid(int value) {
		userid = value;
	}

	public String getName() {
		return name;
	}

	public void setName(String value) {
		name = value;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String value) {
		email = value;
	}

	public String getGsm() {
		return gsm;
	}

	public void setGsm(String value) {
		gsm = value;
	}

	public String getNotes() {
		return notes;
	}

	public void setNotes(String value) {
		notes = value;
	}

	public int getState() {
		return state;
	}

	public void setState(int value) {
		state = value;
	}

}
